"""MaidThis market list, derived from consumer-site URL segments found in
DataForSEO Labs relevant_pages for maidthis.com (see raw/maidthis_relevant_pages*.json).

slug, display name, city used for DataForSEO location matching, state, market type.
"""
MARKETS = [
 ("los-angeles","Los Angeles (corporate)","Los Angeles","CA","corporate"),
 ("losangelesvalley","LA Valley","Los Angeles","CA","territory"),
 ("san-francisco","San Francisco","San Francisco","CA","territory"),
 ("denver","Denver","Denver","CO","territory"),
 ("phoenix","Phoenix","Phoenix","AZ","territory"),
 ("scottsdale","Scottsdale","Scottsdale","AZ","territory"),
 ("saltlakecity","Salt Lake City","Salt Lake City","UT","territory"),
 ("austin","Austin","Austin","TX","territory"),
 ("nw-austin","Northwest Austin","Cedar Park","TX","territory"),
 ("san-antonio","San Antonio","San Antonio","TX","territory"),
 ("nw-sanantonio","Northwest San Antonio","Helotes","TX","territory"),
 ("mckinney","McKinney","McKinney","TX","territory"),
 ("flower-mound","Flower Mound","Flower Mound","TX","territory"),
 ("katy","Katy","Katy","TX","territory"),
 ("spring","Spring","Spring","TX","territory"),
 ("ne-houston","Northeast Houston","Humble","TX","territory"),
 ("chicago","Chicago","Chicago","IL","territory"),
 ("minneapolis","Minneapolis","Minneapolis","MN","territory"),
 ("milwaukee","Milwaukee","Milwaukee","WI","territory"),
 ("fishers","Fishers","Fishers","IN","territory"),
 ("cincinnati","Cincinnati","Cincinnati","OH","territory"),
 ("pittsburgh","Pittsburgh","Pittsburgh","PA","territory"),
 ("philadelphia","Philadelphia","Philadelphia","PA","territory"),
 ("kingofprussia","King of Prussia","King of Prussia","PA","territory"),
 ("jersey-hoboken","Jersey City / Hoboken","Jersey City","NJ","territory"),
 ("boston","Boston","Boston","MA","territory"),
 ("baltimore","Baltimore","Baltimore","MD","territory"),
 ("alexandria","Alexandria","Alexandria","VA","territory"),
 ("arlington","Arlington","Arlington","VA","territory"),
 ("richmond","Richmond","Richmond","VA","territory"),
 ("charlotte","Charlotte","Charlotte","NC","territory"),
 ("durham","Durham","Durham","NC","territory"),
 ("wilmington","Wilmington","Wilmington","NC","territory"),
 ("myrtle-beach","Myrtle Beach","Myrtle Beach","SC","territory"),
 ("columbia","Columbia","Columbia","SC","territory"),
 ("chattanooga","Chattanooga","Chattanooga","TN","territory"),
 ("spring-hill","Spring Hill","Spring Hill","TN","territory"),
 ("atlanta","Atlanta","Atlanta","GA","territory"),
 ("northatlanta","North Atlanta","Alpharetta","GA","territory"),
 ("henry-county","Henry County","McDonough","GA","territory"),
 ("miami","Miami","Miami","FL","territory"),
 ("west-palm-beach","West Palm Beach","West Palm Beach","FL","territory"),
 ("cape-coral","Cape Coral","Cape Coral","FL","territory"),
 ("tampa","Tampa","Tampa","FL","territory"),
 ("east-tampa","East Tampa","Brandon","FL","territory"),
 ("st-petersburg-clearwater","St. Petersburg / Clearwater","Saint Petersburg","FL","territory"),
]

KEYWORDS = [
 "house cleaning services","maid service","cleaning service","airbnb cleaning service",
 "vacation rental cleaning","move out cleaning","deep cleaning service",
 "house cleaning near me","apartment cleaning service","recurring house cleaning",
]
